# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://agustinadefrancesco.github.io/
title: Agustina De Francesco
email: agustinadefrancesco@gmail.com
author: Agustina De Francesco
description: "Agustina's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://agustinadefrancesco.github.io/  
  - icon: envelope-o
    title: email
    url: mailto:agustinadefrancesco@gmail.com
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/agustina-de-francesco-b37a69179/
  - icon: file-pdf-o
    title: CV
    url: agustinadefrancesco.github.io/De Francesco cv april 2019.pdf
#  - icon: website
#    title: CV Lattes
#    url: http://lattes.cnpq.br/5399100590606067
  - icon: twitter
    title: twitter
    url: https://twitter.com/agustinadefranc

